<?php

/**
 * @file
 * send_emails.module
 */ 


/**
 * Implements hook_mail()
 */
function send_emails_mail($key, &$message, $params) {
    
    if (substr($key, 0, strlen('send_emails.template.')) == 'send_emails.template.') {        
        $message['subject'] = $params['message']['subject'];
        $message['body'] = array_merge($message['body'], $params['message']['body']);
        $message['headers'] = $params['message']['headers'];
        $message['params'] = $params['message']['params'];
    }

}















